### ISSUE TITLE
TryLock触发KeepAliveTask?

### ISSUE THREAD

**Issue by linyvxiang** [fxsjy/ins#10]
当前TryLock时不会触发后台启动KeepAliveTask线程，如果客户端直接调用TryLock，那么服务端是没有这个客户的session的，在服务端判断LockIsAvilable时，会尝试从leveldb读取相应的key，若读取不到，则再判断当前session是不是在session列表中，若在，则允许加锁（ins_node_impl.cc 1030行）。
这样的话，若用户直接调用TryLock之前，没有调用过TryLock，则所有的TryLock操作都不会成功。这里是不是需要改变一下？

**Comment by linyvxiang** [comment]
#12

**Comment by fxsjy** [comment]
@linyvxiang ， 是的。 Try的意思就是可能会失败，需要用户自己处理。
不过，如果用户直接调用TryLock而不是Lock的话，的确不会启动session心跳，是个bug。
