### ISSUE TITLE
better input ( readline )

### ISSUE THREAD

**Issue by taocp** [fxsjy/ins#3]
https://github.com/fxsjy/ins/blob/master/sandbox/ins_shell.sh#L4

`read -p "galaxy ins> " cmd arg1 arg2` 不支持backspace等按键

如此这般，赶脚好一点： `read -e -p "galaxy ins> " cmd arg1 arg2`.
`man 1 read` 
```bash
 -e     If  the  standard input is coming from a terminal, readline (see READLINE above) is used
         to obtain the line.
```

**Comment by fxsjy** [comment]
请发pull request
